import React,{useEffect,useState}from'react';import{Activity,ArrowLeft,CheckCircle2,Clock3,Database,FileSearch,GraduationCap,Search,ShieldCheck,Sparkles,Users,XCircle}from'lucide-react';import{getLearners,getLearner,analyze,review,audit}from'./services/api';
function App(){const[learners,setLearners]=useState([]),[selected,setSelected]=useState(null),[profile,setProfile]=useState(null),[analysis,setAnalysis]=useState(null),[logs,setLogs]=useState([]),[loading,setLoading]=useState(false),[q,setQ]=useState('');useEffect(()=>{getLearners().then(setLearners);},[]);
const open=async id=>{setSelected(id);setAnalysis(null);setProfile(await getLearner(id));};
const run=async()=>{setLoading(true);const r=await analyze(selected);setAnalysis(r);setLogs(await audit());setLoading(false)};
const decide=async d=>{await review({run_id:analysis.run_id,learner_id:selected,decision:d,patterns:analysis.patterns});setAnalysis(null);setProfile(await getLearner(selected));setLogs(await audit())};
const filtered=learners.filter(x=>(x.name+x.learner_id).toLowerCase().includes(q.toLowerCase()));
return <div className="app"><header><div className="brand"><div className="logo"><GraduationCap size={24}/></div><div><b>EduLongView</b><span>Teacher intelligence workspace</span></div></div><div className="pill"><ShieldCheck size={16}/> Human-led AI</div></header>
<main>{!selected?<><section className="hero"><div><div className="eyebrow">THE LONG VIEW</div><h1>See the learner beyond a single term.</h1><p>Evidence-grounded AI helps teachers identify longitudinal learning patterns while keeping consequential decisions in human hands.</p><button onClick={()=>open('LRN-0042')}><Sparkles size={18}/> Open demo learner</button></div><div className="hero-card"><div className="hero-icon"><FileSearch/></div><h3>Evidence first</h3><p>Every meaningful finding is tied to identifiable learner evidence.</p></div></section>
<div className="section-head"><div><h2>Learners</h2><p>Synthetic demo cohort</p></div><div className="search"><Search size={17}/><input placeholder="Search learner..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="grid">{filtered.map(l=><button className="learner-card" key={l.learner_id} onClick={()=>open(l.learner_id)}><div className="avatar">{l.name[0]}</div><div><b>{l.name}</b><span>{l.learner_id} · {l.grade}</span></div><ArrowLeft className="rotate" size={17}/></button>)}</div></>:
<><button className="back" onClick={()=>setSelected(null)}><ArrowLeft size={17}/> All learners</button><section className="profile-head"><div className="avatar big">{profile?.learner?.name?.[0]}</div><div><div className="eyebrow">LEARNER PROFILE</div><h1>{profile?.learner?.name}</h1><p>{selected} · {profile?.learner?.grade}</p></div><button className="analyze" onClick={run} disabled={loading}>{loading?<Clock3 className="spin"/>:<Sparkles size={18}/>} {loading?'Analyzing…':'Analyze learner'}</button></section>
{analysis&&<section className="review"><div className="review-title"><div><span className="status">HUMAN REVIEW REQUIRED</span><h2>Agent analysis</h2></div><button className="icon-btn" onClick={()=>setAnalysis(null)}><XCircle/></button></div><div className="notice">AI-generated analysis. Teacher review is required before profile updates.</div><div className="patterns">{analysis.patterns.map((p,i)=><div className="pattern" key={i}><div className="pattern-top"><b>{p.pattern}</b><span>{p.confidence}</span></div><small>{p.category}</small><div className="evidence-row">{p.evidence_ids.map(id=><span key={id}><FileSearch size={14}/>{id}</span>)}</div></div>)}</div>{analysis.gaps.length>0&&<div className="gap"><b>Evidence gaps</b>{analysis.gaps.map(g=><div key={g}>{g}</div>)}</div>}<div className="actions"><button className="reject" onClick={()=>decide('rejected')}><XCircle size={17}/> Reject</button><button onClick={()=>decide('approved')}><CheckCircle2 size={17}/> Approve & update</button></div></section>}
<div className="columns"><section className="panel"><div className="panel-head"><div><h2>Longitudinal overview</h2><p>Available assessment history</p></div><Database/></div>{profile?.assessments?.map((a,i)=><div className="evidence" key={a.evidence_id}><div className="dot"></div><div className="ev-main"><b>{a.subject} · {a.type}</b><span>{a.term} · Evidence {a.evidence_id}</span><p>{a.note}</p></div><strong>{a.score}%</strong></div>)}</section>
<section className="panel"><div className="panel-head"><div><h2>Agent activity</h2><p>Auditable workflow</p></div><Activity/></div>{logs.filter(x=>x.learner_id===selected).slice(0,8).map(x=><div className="log" key={x.id}><span>{new Date(x.created_at).toLocaleTimeString()}</span><b>{x.step}</b><em>{x.status}</em></div>)}{logs.filter(x=>x.learner_id===selected).length===0&&<div className="empty">Run an analysis to see real agent and MCP activity.</div>}</section></div></>}</main><footer>EduLongView · Synthetic data prototype · AI assists; teachers decide.</footer></div>}
export default App;
